apiVersion: v1
kind: Pod
spec:
  tolerations:
    - effect: NoSchedule
      key: am-name
      operator: Equal
      value: spark
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: am-name
                operator: In
                values:
                  - spark